sudo: required
  - docker

before_install:
  - docker build -t icefeast/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run icefeast/react-test npm test

after_success:
  - docker build -t icefeast/multi-client ./client
  - docker build -t icefeast/multi-server ./server
  - docker build -t icefeast/multi-worker ./worker
  - docker build -t icefeast/multi-nginx ./nginx
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - docker push icefeast/multi-client
  - docker push icefeast/multi-server
  - docker push icefeast/multi-worker
  - docker push icefeast/multi-nginx